/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,tsx}',
    './components/**/*.{js,tsx}',
    '.src/app/**/*.{js,tsx}',
    './src/**/*.{js,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: 'var(--gap)',
      screens: {
        '2xl': '1400px',
      },
    },
    fontSize: {
      xs4: ['10px', '22px'],
      xs3: ['11px', '24px'],
      xs2: ['12px', '14px'],
      xs2_1: ['12px', '19px'],
      xs: ['13px', '18px'],
      md: ['14px', '22px'],
      md2: ['15px', '16px'],
      base: ['16px', '24px'],
      base1: ['17px', '24px'],
      base2: ['16px', '16px'],
      xl: ['18px', '24px'],
      xl2: ['20px', '28px'],
      xl12: ['22px', '26px'],
      xl3: ['24px', '32px'],
      xl35: ['28px', '32px'],
      xl4: ['30px', '32px'],
      xl4m: ['30px', '39px'],
      xl45: ['32px', '34px'],
      xl5: ['34px', '32px'],
      xl6: ['40px', '32px'],
      xl7: ['72px', '86px'],
    },
    extend: {
      screens: {
        shortHeight: { raw: '(max-height: 700px)' },
      },
      transitionDuration: {
        2000: '2000ms',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        shake: {
          '20%': { transform: 'translateX(0px)' },
          '30%': { transform: 'translateX(20px)' },
          '40%': { transform: 'translateX(-20px)' },
          '50%': { transform: 'translateX(-15px)' },
          '60%': { transform: 'translateX(10px)' },
          '70%': { transform: 'translateX(-10px)' },
          '80%': { transform: 'translateX(0px)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        shine: {
          '0%': { left: '-75%' },
          '100%': { left: '125%' },
        },
        slideDown: {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        slideUp: {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shake: 'shake 0.5s 0.2s ease-out',
        'fade-in': 'fadeIn 1s ease-out forwards',
        shine: 'shine 5s infinite',
        slideDown: 'slideDown 300ms cubic-bezier(0.87, 0, 0.13, 1)',
        slideUp: 'slideUp 300ms cubic-bezier(0.87, 0, 0.13, 1)',
      },
      gridTemplateColumns: {
        auto: 'auto auto',
      },
      backgroundImage: {
        gradient: 'var(--gradient)',
        tick: "url('./tick.svg')",
        tickGreen: "url('./tick-green.svg')",
        more: 'linear-gradient(270deg, #F6F7F9 63.54%, rgba(246, 247, 249, 0) 91.43%);',
        progressLinear:
          'linear-gradient(90deg, rgba(98,218,24,1) 0%, rgba(255,232,28,1) 50%, rgba(234,74,58,1) 100%)',
        progressLinearBetterme:
          'linear-gradient(90deg, #96d9ff, #b7f5a8 31.77%, #f9eb7c 66.15%, #fc806e)',
        brandRadial: 'var(--bgRadial)',
        brandRadialInside: 'var(--bgRadialInside)',
        brandRadialFooter: 'var(--bgRadialFooter)',
        brandRenewRadialFooter: 'var(--bgRenewRadialFooter)',
      },
      maxWidth: {
        content: 'var(--width-container)',
        image: '390px',
      },
      maxHeight: {
        absolute: 'calc(100% - 96px)',
      },
      minWidth: {
        screen: 'var(--width-container)',
        image: '100vw',
        image2: 'calc(100% + 32px)',
        body: '182px',
        price: '92px',
      },
      width: {
        45: '45%',
        image: '100vw',
      },
      height: {
        graph: '503px',
        absolute: 'calc(100% - 96px)',
      },
      spacing: {
        'image-gap': 'var(--gap)',
        71: '71px',
      },
      transitionDelay: {
        1500: '1500ms',
      },
      colors: {
        black: 'var(--black)',
        primary: 'var(--primary)',
        gray: 'var(--gray)',
        dark: 'var(--dark)',
        light: 'var( --light)',
        border: 'var(--border-light)',
        mark: 'var(--mark)',
        progress: 'var(--progress)',
        green: 'var(--green)',
        radio: 'var(--border-radio)',
        checkBorder: 'var(--check-border)',
        borderGrey: 'var(--border-grey)',
        check: 'var(--check-btn)',
        checked: '#ECFBF3',
        dots: '#79787B',
        lightGray: '#FAFAFA',
        darkOpacity: 'var(--darkOpacity)',
        grayB: 'var(--grayB)',
        danger: 'var(--danger)',
        dangerStroke: 'var(--dangerStroke)',
        warning: 'var(--warning)',
        warningStroke: 'var(--warningStroke)',
        good: 'var(--good)',
        goodStroke: 'var(--goodStroke)',
        goalStroke: '#E8E9EB',
        goal: '#F6F7F9',
        olive: '#7BB10A',
        grayA1: 'var(--grayA1)',
        red: 'var(--red)',
        lightBlue: 'var(--lightBlue)',
        timer: '#23E37B',
        plan: 'var(--plan)',
        level: '#D9D9D9',
        green2: 'var(--green2)',
        gray9: '#919CA4',
        grayE: 'var(--grayE)',
        blue: 'var(--blue)',
        borderHeader: 'rgba(23, 23, 23, 0.08)',
        inputBg: 'rgba(0, 0, 0, 0.03)',
        backButtonBorder: 'rgba(179, 179, 179, 0.31)',
        secondary: '#5F626F',
        green3: '#0D9148',
        green4: '#1AC760',
        green5: '#A5EBC1',
        green6: '#D0F5E1',
        border1: '#E2E2E6',
        gameSwipe: {
          left: '#F99494',
          neutral: '#fff',
          right: '#A5EBC5',
        },
      },
      borderRadius: {
        r53: '53px',
        r3: '3px',
        r4: '4px',
        r8: '8px',
        r12: '12px',
        r2: '2px',
        r10: '10px',
        r20: '20px',
        r24: '24px',
        r30: '30px',
        r15: '15px',
        r16: '16px',
      },
      boxShadow: {
        btn: 'var(--btn-shadow)',
        close: 'var(--close-shadow)',
        back: 'var(--back-shadow)',
        green: 'var(--green-shadow)',
        popup: 'var(--popup-shadow)',
        large: 'var(--large-shadow)',
        betterme: '0px 3px 7px rgba(23, 23, 23, 0.06)',
        input: '0 2px 1px 0 #E6EAEF inset',
        card: '0 2px 4px 0 rgba(0, 0, 0, 0.02), 0 1px 2px 0 rgba(0, 0, 0, 0.04)',
        renew: '0 10px 25px 0 rgba(122, 236, 110, 0.26), 0 5px 10px 0 rgba(102, 215, 77, 0.16)',
        header:
          '0 32px 64px 0 rgba(0, 0, 0, 0.02), 0 20px 40px 0 rgba(0, 0, 0, 0.03), 0 12px 28px 0 rgba(0, 0, 0, 0.01)',
      },
      fontFamily: {
        outfit: 'var(--familyOutfit)',
        inter: 'var(--familyInter)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
