import Stage1SvgActive from '@/assets/images/fasting/stage1.svg'
import Stage2SvgActive from '@/assets/images/fasting/stage2.svg'
import Stage3SvgActive from '@/assets/images/fasting/stage3.svg'
import Stage4SvgActive from '@/assets/images/fasting/stage4.svg'
import Stage1Svg from '@/assets/images/fasting/stage-1-white.svg'
import Stage2Svg from '@/assets/images/fasting/stage-2-white.svg'
import Stage3Svg from '@/assets/images/fasting/stage-3-white.svg'
import Stage4Svg from '@/assets/images/fasting/stage-4-white.svg'
import Stage1Progress from '@/assets/images/fasting/stage-1-progress.svg'
import Stage2Progress from '@/assets/images/fasting/stage-2-progress.svg'
import Stage3Progress from '@/assets/images/fasting/stage-3-progress.svg'
import Stage4Progress from '@/assets/images/fasting/stage-4-progress.svg'
import Stage1ProgressLight from '@/assets/images/fasting/stage-1-progress-light.svg'
import Stage2ProgressLight from '@/assets/images/fasting/stage-2-progress-light.svg'
import Stage3ProgressLight from '@/assets/images/fasting/stage-3-progress-light.svg'
import Stage4ProgressLight from '@/assets/images/fasting/stage-4-progress-light.svg'
import Stage1Card from '@/assets/images/fasting/stage-1-card.svg'
import Stage2Card from '@/assets/images/fasting/stage-2-card.svg'
import Stage3Card from '@/assets/images/fasting/stage-3-card.svg'
import Stage4Card from '@/assets/images/fasting/stage-4-card.svg'

import { useTranslation } from 'react-i18next'
import { FastingLevel } from '@/components/pages/FastingPage/types/index.types'

const UseGetModelsData = (): FastingLevel[] => {
  const { t } = useTranslation()

  // return
  return [
    {
      levelName: t('beginners'),
      models: [
        {
          id: '12:12',
          fastingDuration: 12,
          eatingDuration: 12,
          description: t('circadianIntro'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 0,
            },
          ],
        },
        {
          id: '13:11',
          fastingDuration: 13,
          eatingDuration: 11,
          description: t('circadianDescription'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 1,
            },
          ],
        },
        {
          id: '14:10',
          fastingDuration: 14,
          eatingDuration: 10,
          description: t('dietitiansAdvice'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 2,
            },
          ],
        },
        {
          id: '15:9',
          fastingDuration: 15,
          eatingDuration: 9,
          description: t('plan16_8_intro'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 3,
            },
          ],
        },
      ],
    },
    {
      levelName: t('experiencedFasters'),
      models: [
        {
          id: '16:8',
          fastingDuration: 16,
          eatingDuration: 8,
          description: t('plan16_8_advanced'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 4,
            },
          ],
        },
        {
          id: '17:7',
          fastingDuration: 17,
          eatingDuration: 7,
          description: t('fasting17h'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 5,
            },
          ],
        },
        {
          id: '18:6',
          fastingDuration: 18,
          eatingDuration: 6,
          description: t('plan18_6'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 6,
            },
          ],
        },
        {
          id: '19:5',
          fastingDuration: 19,
          eatingDuration: 5,
          description: t('fasting19h'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 7,
            },
          ],
        },
      ],
    },
    {
      levelName: t('proFasters'),
      models: [
        {
          id: '20:4',
          fastingDuration: 20,
          eatingDuration: 4,
          description: t('warriorDiet'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 8,
            },
          ],
        },
        {
          id: '21:3',
          fastingDuration: 21,
          eatingDuration: 3,
          description: t('fasting21h'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 9,
            },
          ],
        },
        {
          id: '22:2',
          fastingDuration: 22,
          eatingDuration: 2,
          description: t('omad'),
          listTitle: t('howToPrepare'),
          list: [
            t('pickFastingType'),
            t('eatHighProtein'),
            t('drinkWater'),
            t('continueActivities'),
          ],
          stages: [
            {
              id: 1,
              activeSvg: Stage1SvgActive,
              svg: Stage1Svg,
              svgProgress: Stage1Progress,
              svgProgressInactive: Stage1ProgressLight,
              svgCard: Stage1Card,
              title: t('bloodSugarRises'),
              descriptionSmall: t('glucoseEntersBloodstream'),
              descriptions: [t('bloodSugarAfterMeal'), t('insulinRole')],
              durationHours: 4,
            },
            {
              id: 2,
              activeSvg: Stage2SvgActive,
              svg: Stage2Svg,
              svgProgress: Stage2Progress,
              svgProgressInactive: Stage2ProgressLight,
              svgCard: Stage2Card,
              title: t('bloodSugarStabilizes'),
              descriptionSmall: t('hormonesConvertGlucose'),
              descriptions: [t('glucagonBalances'), t('switchToFatBurning')],
              durationHours: 4,
            },
            {
              id: 3,
              activeSvg: Stage3SvgActive,
              svg: Stage3Svg,
              svgProgress: Stage3Progress,
              svgProgressInactive: Stage3ProgressLight,
              svgCard: Stage3Card,
              title: t('fatStartsBurning'),
              descriptionSmall: t('bodyUsesStoredFat'),
              descriptions: [t('shiftToFatFuel')],
              durationHours: 4,
            },
            {
              id: 4,
              activeSvg: Stage4SvgActive,
              svg: Stage4Svg,
              svgProgress: Stage4Progress,
              svgProgressInactive: Stage4ProgressLight,
              svgCard: Stage4Card,
              title: t('onsetOfKetosis'),
              descriptionSmall: t('ketoneProduction'),
              descriptions: [t('lowGlucoseAfter12h'), t('ketosisExplanation')],
              durationHours: 10,
            },
          ],
        },
      ],
    },
  ]
}

export default UseGetModelsData
