export const API_URLS = {
  SIGN_IN: '/v1/auth/local/sign-in',
  ACCOUNT: '/v4/account',
  GET_CODE_BY_EMAIL: '/v2/common/otp',
  GET_WORKOUTS_GROUPS: '/v3/view/workouts-group-page',
  GET_WORKOUT: '/v1/view/workout/',
  GET_MEALS_DAYS: '/v1/view/personal-meals-group-page/raw',
  GET_MEAL: '/v1/view/meal/',
  PASSWORD_RESTORE: '/v1/auth/password/restore',
  UPDATE_TOKEN: '/v1/auth/update-token',
  VERIFY_OTP_AUTH: '/v1/common/otp/auth',
  GET_PROFILE: '/v1/view/personal-payment-plan-page',
  UNSUBSCRIBE_MEALS: '/v1/payment/upsale/meals/unsubscribe',
  UNSUBSCRIBE_HUBSPOT: '/v1/payment/hubspot/unsubscribe',
  GET_PERSONAL_TRAINING: '/v1/view/personal-training-page/raw',
  GET_PROGRESS_PERSONAL_TRAINING: '/v1/account/progress/personal-training',
  PATCH_PROGRESS_PERSONAL_TRAINING: '/v1/account/progress/personal-training',
  PATCH_PERSONAL_TRAINING: '/v1/personal-training',
  GET_PLANS: '/v1/view/get-plans',
  GET_USER_CHALLENGE: '/v1/user-challenge',
  GET_USER_CHALLENGE_TROPHIES: '/v1/user-challenge/trophies',
  GET_USER_CHALLENGE_STREAKS: '/v1/user-challenge/streaks',
  GET_USER_CHALLENGE_ACTIVE: '/v1/user-challenge/active',
  GET_USER_CHALLENGE_FINISHED: '/v1/user-challenge/finished',
  GET_USER_CHALLENGE_AVAILABLE: '/v1/user-challenge/available',
}
